# Automatically open PRs to update outdated deps
# See https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "tendermint*"
      - dependency-name: "ibc*"
      - dependency-name: "cosmwasm*"
      - dependency-name: "cw*"
  - package-ecosystem: "cargo"
    directory: "ci/no-std-check"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "tendermint*"
      - dependency-name: "ibc*"
      - dependency-name: "cosmwasm*"
      - dependency-name: "cw*"
  - package-ecosystem: "cargo"
    directory: "ci/cw-check"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "tendermint*"
      - dependency-name: "ibc*"
      - dependency-name: "cosmwasm*"
      - dependency-name: "cw*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
