[package]
name         = "ibc-eureka-core-connection"
version      = { workspace = true }
authors      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
keywords     = [ "blockchain", "cosmos", "ibc", "connection" ]
readme       = "./../README.md"

description = """
    Maintained by `ibc-rs`, contains the implementation of the ICS-03 Connection Semantics and
    re-exports essential data structures and domain types from `ibc-eureka-core-connection-types` crate.
"""

[package.metadata.docs.rs]
all-features = true

[dependencies]
ibc-eureka-core-client           = { workspace = true }
ibc-eureka-core-connection-types = { workspace = true }
ibc-eureka-core-host             = { workspace = true }
ibc-eureka-core-handler-types    = { workspace = true }
ibc-primitives                   = { workspace = true }
ibc-client-wasm-types            = { workspace = true, optional = true }

prost = { workspace = true, optional = true }

[features]
default = [ "std" ]
std = [
  "ibc-eureka-core-client/std",
  "ibc-eureka-core-connection-types/std",
  "ibc-eureka-core-host/std",
  "ibc-eureka-core-handler-types/std",
  "ibc-primitives/std",
  "wasm-client",
]
serde = [
  "ibc-eureka-core-client/serde",
  "ibc-eureka-core-connection-types/serde",
  "ibc-eureka-core-host/serde",
  "ibc-eureka-core-handler-types/serde",
  "ibc-primitives/serde",
]
schema = [
  "ibc-eureka-core-client/schema",
  "ibc-eureka-core-connection-types/schema",
  "ibc-eureka-core-host/schema",
  "ibc-eureka-core-handler-types/schema",
  "ibc-primitives/schema",
  "serde",
  "std",
]
borsh = [
  "ibc-eureka-core-client/borsh",
  "ibc-eureka-core-connection-types/borsh",
  "ibc-eureka-core-host/borsh",
  "ibc-eureka-core-handler-types/borsh",
  "ibc-primitives/borsh",
]
parity-scale-codec = [
  "ibc-eureka-core-client/parity-scale-codec",
  "ibc-eureka-core-connection-types/parity-scale-codec",
  "ibc-eureka-core-host/parity-scale-codec",
  "ibc-eureka-core-handler-types/parity-scale-codec",
  "ibc-primitives/parity-scale-codec",
]
wasm-client = [
  "dep:ibc-client-wasm-types",
  "dep:prost",
]
