[package]
name         = "ibc-eureka-core-host"
version      = { workspace = true }
authors      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
keywords     = [ "blockchain", "cosmos", "ibc", "host" ]
readme       = "./../README.md"

description = """
    Maintained by `ibc-rs`, contains essential top-level traits designed for the seamless integration
    of host chains, facilitating access to the host's storage, the efficient retrieval of states and
    metadata crucial for the execution of any IBC datagrams.
"""

[package.metadata.docs.rs]
all-features = true

[dependencies]
# external dependencies
derive_more     = { workspace = true }
displaydoc      = { workspace = true }
subtle-encoding = { workspace = true }

# ibc dependencies
ibc-eureka-core-client-types     = { workspace = true }
ibc-eureka-core-client-context   = { workspace = true }
ibc-eureka-core-channel-types    = { workspace = true }
ibc-eureka-core-commitment-types = { workspace = true }
ibc-eureka-core-host-types       = { workspace = true }
ibc-eureka-core-handler-types    = { workspace = true }
ibc-primitives                   = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[features]
default = [ "std" ]
std = [
  "displaydoc/std",
  "subtle-encoding/std",
  "ibc-eureka-core-client-types/std",
  "ibc-eureka-core-client-context/std",
  "ibc-eureka-core-channel-types/std",
  "ibc-eureka-core-commitment-types/std",
  "ibc-eureka-core-host-types/std",
  "ibc-eureka-core-handler-types/std",
  "ibc-primitives/std",
]
serde = [
  "ibc-eureka-core-client-types/serde",
  "ibc-eureka-core-client-context/serde",
  "ibc-eureka-core-channel-types/serde",
  "ibc-eureka-core-commitment-types/serde",
  "ibc-eureka-core-host-types/serde",
  "ibc-eureka-core-handler-types/serde",
  "ibc-primitives/serde",
]
schema = [
  "ibc-eureka-core-client-types/schema",
  "ibc-eureka-core-client-context/schema",
  "ibc-eureka-core-channel-types/schema",
  "ibc-eureka-core-commitment-types/schema",
  "ibc-eureka-core-host-types/schema",
  "ibc-eureka-core-handler-types/schema",
  "ibc-primitives/schema",
  "serde",
  "std",
]
borsh = [
  "ibc-eureka-core-client-types/borsh",
  "ibc-eureka-core-client-context/borsh",
  "ibc-eureka-core-channel-types/borsh",
  "ibc-eureka-core-commitment-types/borsh",
  "ibc-eureka-core-host-types/borsh",
  "ibc-eureka-core-handler-types/borsh",
  "ibc-primitives/borsh",
]
parity-scale-codec = [
  "ibc-eureka-core-client-types/parity-scale-codec",
  "ibc-eureka-core-channel-types/parity-scale-codec",
  "ibc-eureka-core-commitment-types/parity-scale-codec",
  "ibc-eureka-core-host-types/parity-scale-codec",
  "ibc-eureka-core-handler-types/parity-scale-codec",
  "ibc-primitives/parity-scale-codec",
]
