[package]
name         = "ibc-core-channel"
version      = { workspace = true }
authors      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
keywords     = [ "blockchain", "cosmos", "ibc", "channel" ]
readme       = "./../README.md"

description = """
    Maintained by `ibc-rs`, contains the implementation of the ICS-04 Channel & Packet Semantics and
    re-exports essential data structures and domain types from `ibc-core-channel-types` crate.
"""

[package.metadata.docs.rs]
all-features = true

[dependencies]
ibc-core-client           = { workspace = true }
ibc-core-connection       = { workspace = true }
ibc-core-channel-types    = { workspace = true }
ibc-core-commitment-types = { workspace = true }
ibc-core-host             = { workspace = true }
ibc-core-handler-types    = { workspace = true }
ibc-core-router           = { workspace = true }
ibc-primitives            = { workspace = true }

[features]
default = [ "std" ]
std = [
  "ibc-core-client/std",
  "ibc-core-connection/std",
  "ibc-core-channel-types/std",
  "ibc-core-commitment-types/std",
  "ibc-core-host/std",
  "ibc-core-handler-types/std",
  "ibc-core-router/std",
  "ibc-primitives/std",
]
serde = [
  "ibc-core-client/serde",
  "ibc-core-connection/serde",
  "ibc-core-channel-types/serde",
  "ibc-core-commitment-types/serde",
  "ibc-core-host/serde",
  "ibc-core-handler-types/serde",
  "ibc-core-router/serde",
  "ibc-primitives/serde",
]
schema = [
  "ibc-core-client/schema",
  "ibc-core-connection/schema",
  "ibc-core-channel-types/schema",
  "ibc-core-commitment-types/schema",
  "ibc-core-host/schema",
  "ibc-core-handler-types/schema",
  "ibc-core-router/schema",
  "ibc-primitives/schema",
  "serde",
  "std",
]
borsh = [
  "ibc-core-client/borsh",
  "ibc-core-connection/borsh",
  "ibc-core-channel-types/borsh",
  "ibc-core-commitment-types/borsh",
  "ibc-core-host/borsh",
  "ibc-core-handler-types/borsh",
  "ibc-core-router/borsh",
  "ibc-primitives/borsh",
]
parity-scale-codec = [
  "ibc-core-client/parity-scale-codec",
  "ibc-core-connection/parity-scale-codec",
  "ibc-core-channel-types/parity-scale-codec",
  "ibc-core-commitment-types/parity-scale-codec",
  "ibc-core-host/parity-scale-codec",
  "ibc-core-handler-types/parity-scale-codec",
  "ibc-core-router/parity-scale-codec",
  "ibc-primitives/parity-scale-codec",
]
