[package]
name         = "ibc-client-tendermint-cw"
authors      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
rust-version = { workspace = true }
version      = { workspace = true }
keywords     = [ "ibc", "light-client", "CosmWasm", "ICS-07", "Tendermint" ]
readme       = "./README.md"

description = """
    Contains the implementation of the ICS-07 Tendermint Client logic as a CosmWasm contract.
    It leverages the `ibc-client-cw` crate to integrate the Tendermint light client into a CosmWasm contract.
"""

[dependencies]
# external dependencies
derive_more = { workspace = true }
prost       = { workspace = true }
serde       = { workspace = true, features = [ "derive" ] }

# ibc dependencies
ibc-client-tendermint = { workspace = true }
ibc-client-cw         = { workspace = true }
ibc-core              = { workspace = true }

# cosmwasm dependencies
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
cw-storage-plus = { workspace = true }

[dev-dependencies]
serde-json = { workspace = true }

[features]
default = [ "std" ]
std = [
  "prost/std",
  "serde/std",
  "ibc-client-tendermint/std",
  "ibc-client-cw/std",
  "ibc-core/std",
]
