name: Code Quality Checks
on:
  pull_request:
    paths:
      - .github/workflows/code-quality.yaml
      - '*.toml'
      - ci/**
      - cosmwasm/**
      - ibc/**
      - ibc-core/**
      - ibc-apps/**
      - ibc-data-types/**
      - ibc-clients/**
      - ibc-primitives/**
      - ibc-query/**
      - ibc-testkit/**
      - ibc-derive/**
      - tests-integration/**
  push:
    tags:
      - v[0-9]+.*
    branches:
      - "release/*"
      - main

jobs:
  code-quality:
    name: Check Code Quality
    runs-on: ubuntu-latest
    env:
      RIPGREP_VERSION: 14.1.0
      FD_VERSION: 9.0.0
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly toolchain with rustfmt
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt
      - name: Install Rust stable toolchain with clippy
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Taplo
        uses: baptiste0928/cargo-install@v3
        with:
            crate: taplo-cli
      - name: Run Lint Checks (fmt, clippy, taplo)
        run: make lint
      - name: Spell Check with Typos
        uses: crate-ci/typos@master
        with:
            config: ./.github/typos.toml
