name: Code Quality Checks
on:
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    env:
      RIPGREP_VERSION: 14.1.0
      FD_VERSION: 9.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Whitestapace lints
        run: bash ci/code-quality/whitespace-lints.sh

      - name: Spell Check with Typos
        uses: crate-ci/typos@v1.22.7
        with:
          config: ./.github/typos.toml

      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: taplo-cli
      - run: taplo fmt --check
