name: Check Markdown links

on:
  schedule:
    - cron: "0 0 * * *" # At 00:00
  pull_request:

jobs:
  md-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          config-file: ".github/markdown-link-check.json"
          use-quiet-mode: "yes"
          folder-path: ${{ github.event_name == 'pull_request' && 'docs' || '.' }}
